routes:
  - prefix: /api/v1/auth
    target: http://auth-service:3001
    auth: false

  - prefix: /api/v1/users
    target: http://user-service:3002
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/chefs
    target: http://chef-service:3003
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/orders
    target: http://order-service:3004
    auth: true
    roles:
      - USER
      - CHEF

  - prefix: /api/v1/admin
    target: http://admin-service:3005
    auth: true
    roles:
      - ADMIN

  - prefix: /api/v1/notifications
    target: http://notification-service:3006
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN
