routes:
  - prefix: /api/v1/auth
    targetKey: AUTH_SERVICE_URL
    auth: false

  - prefix: /api/v1/payments/webhook
    targetKey: PAYMENT_SERVICE_URL
    auth: false

  - prefix: /api/v1/payments
    targetKey: PAYMENT_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/users
    targetKey: USER_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/discovery/chefs
    targetKey: CHEF_SERVICE_URL
    auth: false

  - prefix: /api/v1/reviews/public
    targetKey: REVIEW_SERVICE_URL
    auth: false

  - prefix: /api/v1/reviews
    targetKey: REVIEW_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/discovery/dishes
    targetKey: CHEF_SERVICE_URL
    auth: false

  - prefix: /api/v1/chefs
    targetKey: CHEF_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/orders
    targetKey: ORDER_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF

  - prefix: /api/v1/subscriptions
    targetKey: SUBSCRIPTION_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/admin
    targetKey: ADMIN_SERVICE_URL
    auth: true
    roles:
      - ADMIN

  - prefix: /api/v1/notifications
    targetKey: NOTIFICATION_SERVICE_URL
    auth: true
    roles:
      - USER
      - CHEF
      - ADMIN

  - prefix: /api/v1/media
    targetKey: MEDIA_SERVICE_URL
    auth: true
