import type { ChefProfile, Dish, MealPlan, Order } from '../types/domain'

export const mockChefs: ChefProfile[] = [
  {
    id: 'chef-ayesha-khan',
    userId: 'user-ayesha-khan',
    displayName: 'Ayesha Khan',
    bio: 'Punjabi home cooking with a generous table and seasonal ingredients.',
    cuisineSpecialties: ['Punjabi', 'Home cooking'],
    verificationStatus: 'ACTIVE',
    serviceArea: { city: 'Lahore', neighborhood: 'Gulberg' },
    portfolioMediaIds: ['media-ayesha-kitchen', 'media-ayesha-table'],
    averageRating: 4.9,
    totalReviews: 128,
    profileImageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=80',
    accountState: 'ACTIVE',
  },
  {
    id: 'chef-hamza-malik',
    userId: 'user-hamza-malik',
    displayName: 'Hamza Malik',
    bio: 'Coastal flavours, charcoal cooking, and Karachi-inspired comfort food.',
    cuisineSpecialties: ['Coastal', 'Pakistani'],
    verificationStatus: 'ACTIVE',
    serviceArea: { city: 'Karachi', neighborhood: 'Clifton' },
    portfolioMediaIds: ['media-hamza-grill'],
    averageRating: 4.8,
    totalReviews: 94,
    profileImageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80',
    accountState: 'ACTIVE',
  },
  {
    id: 'chef-sara-ahmed',
    userId: 'user-sara-ahmed',
    displayName: 'Sara Ahmed',
    bio: 'Seasonal vegetable cooking with bright, generous plates.',
    cuisineSpecialties: ['Seasonal', 'Vegetarian'],
    verificationStatus: 'ACTIVE',
    serviceArea: { city: 'Islamabad', neighborhood: 'F-7' },
    portfolioMediaIds: ['media-sara-garden'],
    averageRating: 4.9,
    totalReviews: 76,
    profileImageUrl: 'https://images.unsplash.com/photo-1556761223-4c4282c73f77?auto=format&fit=crop&w=900&q=80',
    accountState: 'ACTIVE',
  },
]

export const mockDishes: Dish[] = [
  {
    id: 'dish-smoky-karahi',
    chefId: 'chef-ayesha-khan',
    name: 'Smoky karahi',
    description: 'A slow-built tomato karahi finished with green chilli and coriander.',
    cuisine: 'Punjabi',
    price: 2400,
    currency: 'PKR',
    ingredients: ['Chicken', 'Tomato', 'Green chilli', 'Coriander'],
    dietaryTags: ['Halal'],
    allergens: [],
    category: 'Main course',
    occasionTags: ['Family dinner'],
    averageRating: 4.9,
    totalReviews: 63,
    status: 'ACTIVE',
    availability: { isAvailable: true, availableDays: ['FRIDAY', 'SATURDAY'] },
    media: [{ id: 'media-smoky-karahi', url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80', type: 'IMAGE' }],
  },
  {
    id: 'dish-sea-salt-pulao',
    chefId: 'chef-hamza-malik',
    name: 'Sea salt pulao',
    description: 'Fragrant rice with coastal spices, toasted nuts, and seasonal herbs.',
    cuisine: 'Coastal Pakistani',
    price: 2800,
    currency: 'PKR',
    ingredients: ['Basmati rice', 'Cardamom', 'Cashews', 'Herbs'],
    dietaryTags: ['Halal'],
    allergens: ['Nuts'],
    category: 'Main course',
    occasionTags: ['Gathering'],
    averageRating: 4.8,
    totalReviews: 51,
    status: 'ACTIVE',
    availability: { isAvailable: true, availableDays: ['SATURDAY', 'SUNDAY'] },
    media: [{ id: 'media-sea-salt-pulao', url: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80', type: 'IMAGE' }],
  },
  {
    id: 'dish-garden-daal',
    chefId: 'chef-sara-ahmed',
    name: 'Garden daal',
    description: 'Silky lentils with charred greens, lemon, and a warm spice tempering.',
    cuisine: 'Seasonal Pakistani',
    price: 1900,
    currency: 'PKR',
    ingredients: ['Lentils', 'Spinach', 'Lemon', 'Cumin'],
    dietaryTags: ['Vegetarian', 'Halal'],
    allergens: [],
    category: 'Main course',
    occasionTags: ['Weeknight'],
    averageRating: 4.9,
    totalReviews: 37,
    status: 'ACTIVE',
    availability: { isAvailable: true, availableDays: ['WEDNESDAY', 'THURSDAY'] },
    media: [{ id: 'media-garden-daal', url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=80', type: 'IMAGE' }],
  },
]

export const mockMealPlans: MealPlan[] = [
  {
    id: 'plan-sunday-dastarkhwan',
    chefId: 'chef-ayesha-khan',
    name: 'The Sunday Dastarkhwan',
    description: 'A generous weekly spread built for slow Sundays and a full table.',
    type: 'SUBSCRIPTION',
    frequency: 'WEEKLY',
    status: 'ACTIVE',
    tiers: [{ name: 'Gathering', serves: '2–4 people', price: 8400 }],
    basePrice: 8400,
    currency: 'PKR',
    availabilityRules: ['Order by Thursday at 18:00', 'Lahore delivery on Sunday'],
    pauseRules: ['Pause up to 48 hours before delivery'],
    skipRules: ['Skip one week from your plan page'],
    swapRules: ['Swap one side each week'],
    mediaIds: ['media-sunday-dastarkhwan'],
    averageRating: 4.9,
    totalReviews: 42,
  },
  {
    id: 'plan-seasonal-bazaar',
    chefId: 'chef-sara-ahmed',
    name: 'Seasonal Bazaar',
    description: 'A biweekly basket of bright, market-led dishes for the curious table.',
    type: 'SUBSCRIPTION',
    frequency: 'BIWEEKLY',
    status: 'ACTIVE',
    tiers: [{ name: 'Market table', serves: '2–4 people', price: 11000 }],
    basePrice: 11000,
    currency: 'PKR',
    availabilityRules: ['Order by Monday at 18:00', 'Islamabad delivery every other Saturday'],
    pauseRules: ['Pause before the next menu is announced'],
    skipRules: ['Skip any upcoming delivery'],
    swapRules: ['Swap one dish for a seasonal alternative'],
    mediaIds: ['media-seasonal-bazaar'],
    averageRating: 4.8,
    totalReviews: 28,
  },
  {
    id: 'plan-family-hearth',
    chefId: 'chef-hamza-malik',
    name: 'The Family Hearth',
    description: 'A monthly coastal-inspired spread with enough room for everyone to linger.',
    type: 'SUBSCRIPTION',
    frequency: 'MONTHLY',
    status: 'ACTIVE',
    tiers: [{ name: 'Family table', serves: '4–6 people', price: 16800 }],
    basePrice: 16800,
    currency: 'PKR',
    availabilityRules: ['Order by the 20th', 'Karachi delivery on the first Saturday'],
    pauseRules: ['Pause before the next month begins'],
    skipRules: ['Skip any future month'],
    swapRules: ['Swap up to two dishes each month'],
    mediaIds: ['media-family-hearth'],
    averageRating: 4.8,
    totalReviews: 31,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-demo-001',
    customerId: 'customer-demo',
    chefId: 'chef-ayesha-khan',
    status: 'CONFIRMED',
    deliveryDate: '2026-08-29',
    total: 2400,
    currency: 'PKR',
  },
]

export function createMockRepository<T extends { id: string }>(records: readonly T[]) {
  return {
    async list(): Promise<T[]> {
      return records.map((record) => ({ ...record }))
    },
    async getById(id: string): Promise<T | null> {
      const record = records.find((item) => item.id === id)
      return record ? { ...record } : null
    },
  }
}

export const mockRepositories = {
  chefs: createMockRepository(mockChefs),
  dishes: createMockRepository(mockDishes),
  mealPlans: createMockRepository(mockMealPlans),
  orders: createMockRepository(mockOrders),
}
