import { Link, useParams } from 'react-router-dom'
import { mockChefs, mockDishes, mockMealPlans } from '../services/mockRepository'
import { BackToDiscover, PageHeading, PublicPageShell } from './PublicPageShell'

function MissingResult({ kind }: { kind: string }) {
  return <PublicPageShell><main className="mx-auto max-w-[1500px] px-4 py-20 sm:px-8 lg:px-12"><PageHeading title={`${kind} not found`} copy="That demo listing may have moved. Return to discovery to browse the current catalog." /><Link to="/discover" className="mt-8 inline-flex min-h-11 items-center rounded-pill bg-terracotta px-5 text-sm font-semibold text-cream hover:bg-terracotta-dark focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-terracotta">Back to discovery</Link></main></PublicPageShell>
}

export function ChefDetailPage() {
  const { chefId } = useParams()
  const chef = mockChefs.find((item) => item.id === `chef-${chefId}` || item.id === chefId)
  if (!chef) return <MissingResult kind="Chef" />
  const dishes = mockDishes.filter((dish) => dish.chefId === chef.id)
  const plans = mockMealPlans.filter((plan) => plan.chefId === chef.id)
  return <PublicPageShell><main className="mx-auto max-w-[1500px] px-4 py-12 sm:px-8 lg:px-12 lg:py-20 2xl:px-16"><BackToDiscover /><div className="mt-10 grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-center"><img className="aspect-square w-full max-w-xl rounded-[2rem] object-cover shadow-lg" src={chef.profileImageUrl} alt={chef.displayName} /><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-terracotta">Verified chef · {chef.verificationStatus}</p><h1 className="mt-4 font-display text-6xl leading-[0.95] tracking-[-0.04em] sm:text-8xl">{chef.displayName}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-charcoal-70">{chef.bio}</p><div className="mt-8 flex flex-wrap gap-2">{chef.cuisineSpecialties.map((specialty) => <span key={specialty} className="rounded-pill bg-cream-dim px-4 py-2 text-sm font-semibold">{specialty}</span>)}</div><div className="mt-8 grid grid-cols-2 gap-4 border-y border-charcoal/10 py-5 sm:grid-cols-3"><div><p className="text-2xl font-semibold">★ {chef.averageRating}</p><p className="text-sm text-charcoal-70">{chef.totalReviews} reviews</p></div><div><p className="text-2xl font-semibold">{chef.serviceArea.city}</p><p className="text-sm text-charcoal-70">{chef.serviceArea.neighborhood}</p></div><div><p className="text-2xl font-semibold">0.92</p><p className="text-sm text-charcoal-70">textScore</p></div></div></div></div><section className="mt-20" aria-labelledby="chef-menu"><h2 id="chef-menu" className="font-display text-4xl">What {chef.displayName.split(' ')[0]} is cooking</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{dishes.map((dish) => <Link key={dish.id} to={`/dishes/${dish.id.replace(/^dish-/, '')}`} className="rounded-2xl bg-cream-dim p-5 hover:bg-terracotta-10 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta"><div className="flex justify-between gap-3"><h3 className="font-semibold">{dish.name}</h3><span className="text-sm font-semibold text-terracotta">PKR {dish.price.toLocaleString()}</span></div><p className="mt-2 text-sm text-charcoal-70">{dish.description}</p></Link>)}{plans.map((plan) => <Link key={plan.id} to={`/plans/${plan.id.replace(/^plan-/, '')}`} className="rounded-2xl bg-espresso p-5 text-cream hover:bg-charcoal focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-saffron"><div className="flex justify-between gap-3"><h3 className="font-display text-2xl">{plan.name}</h3><span className="text-sm font-semibold text-saffron">PKR {plan.basePrice.toLocaleString()}</span></div><p className="mt-2 text-sm text-cream/70">{plan.frequency} · {plan.tiers[0].serves}</p></Link>)}</div></section></main></PublicPageShell>
}

export function DishDetailPage() {
  const { dishId } = useParams()
  const dish = mockDishes.find((item) => item.id === `dish-${dishId}` || item.id === dishId)
  if (!dish) return <MissingResult kind="Dish" />
  const chef = mockChefs.find((item) => item.id === dish.chefId)
  return <PublicPageShell><main className="mx-auto max-w-[1500px] px-4 py-12 sm:px-8 lg:px-12 lg:py-20 2xl:px-16"><BackToDiscover /><div className="mt-10 grid gap-10 lg:grid-cols-2"><img className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-lg" src={dish.media[0].url} alt={dish.name} /><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-terracotta">{dish.cuisine} · {dish.category}</p><PageHeading title={dish.name} copy={dish.description} /><p className="mt-8 font-display text-4xl">PKR {dish.price.toLocaleString()}</p><p className="mt-3 text-sm text-charcoal-70">★ {dish.averageRating} from {dish.totalReviews} reviews · {dish.status} · textScore 0.89</p><div className="mt-8 flex flex-wrap gap-3"><Link to={`/cart?item=${dish.id}`} className="inline-flex min-h-11 items-center rounded-pill bg-terracotta px-5 text-sm font-semibold text-cream hover:bg-terracotta-dark focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-terracotta">Add to cart</Link>{chef && <Link to={`/chefs/${chef.id.replace(/^chef-/, '')}`} className="inline-flex min-h-11 items-center rounded-pill border border-charcoal/20 px-5 text-sm font-semibold hover:border-terracotta hover:text-terracotta focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-terracotta">Meet {chef.displayName}</Link>}</div><dl className="mt-10 grid gap-4 border-t border-charcoal/10 pt-6 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-charcoal-70">Ingredients</dt><dd className="mt-2 text-sm">{dish.ingredients.join(' · ')}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-charcoal-70">Availability</dt><dd className="mt-2 text-sm">{dish.availability.availableDays.join(' · ')}</dd></div></dl></div></div></main></PublicPageShell>
}

export function PlanDetailPage() {
  const { planId } = useParams()
  const plan = mockMealPlans.find((item) => item.id === `plan-${planId}` || item.id === planId)
  if (!plan) return <MissingResult kind="Meal plan" />
  const chef = mockChefs.find((item) => item.id === plan.chefId)
  return <PublicPageShell><main className="mx-auto max-w-[1500px] px-4 py-12 sm:px-8 lg:px-12 lg:py-20 2xl:px-16"><BackToDiscover /><div className="mt-10 overflow-hidden rounded-[2rem] bg-espresso text-cream"><div className="grid gap-10 p-6 sm:p-10 lg:grid-cols-[1.2fr_0.8fr] lg:p-16"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-saffron">{plan.frequency} · {plan.type === 'SUBSCRIPTION' ? 'Recurring plan' : 'One-off'}</p><h1 className="mt-5 max-w-2xl font-display text-6xl leading-[0.95] tracking-[-0.04em] sm:text-8xl">{plan.name}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-cream/75">{plan.description}</p>{chef && <Link to={`/chefs/${chef.id.replace(/^chef-/, '')}`} className="mt-7 inline-block text-sm font-semibold text-saffron hover:text-cream focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-saffron">Prepared by {chef.displayName} →</Link>}</div><div className="rounded-2xl bg-cream p-6 text-charcoal"><p className="text-sm text-charcoal-70">{plan.tiers[0].serves}</p><p className="mt-3 font-display text-4xl">PKR {plan.basePrice.toLocaleString()}</p><p className="mt-2 text-sm text-charcoal-70">★ {plan.averageRating} · {plan.totalReviews} reviews · textScore 0.87</p><Link to={`/cart?item=${plan.id}`} className="mt-7 inline-flex min-h-11 w-full items-center justify-center rounded-pill bg-terracotta px-5 text-sm font-semibold text-cream hover:bg-terracotta-dark focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-terracotta">Add plan to cart</Link></div></div></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-cream-dim p-5"><h2 className="font-semibold">Availability</h2><p className="mt-3 text-sm leading-6 text-charcoal-70">{plan.availabilityRules.join(' · ')}</p></div><div className="rounded-2xl bg-cream-dim p-5"><h2 className="font-semibold">Pause & skip</h2><p className="mt-3 text-sm leading-6 text-charcoal-70">{plan.pauseRules[0]} {plan.skipRules[0]}</p></div><div className="rounded-2xl bg-cream-dim p-5"><h2 className="font-semibold">Swap rules</h2><p className="mt-3 text-sm leading-6 text-charcoal-70">{plan.swapRules.join(' · ')}</p></div></div></main></PublicPageShell>
}
